### ISSUE TITLE
Problems with running mycli in the development environment

### ISSUE THREAD

**Issue by ThinkingAgain** [dbcli/mycli#1091]
When I build the mycli development environment and run it for the first time, the following error occurs:
```
Traceback (most recent call last):
  File "mycli/main.py", line 42, in <module>
    from .packages.special.main import NO_QUERY
ImportError: attempted relative import with no known parent package
```
When I removed the dot before packages of line 42:
```
from packages.special.mian import NO_QUERY
```
 the error disappeared, what is the problem?

**Comment by ThinkingAgain** [comment]
Yes, I running the file` main.py` directly! Because I want to study the code. 
I'm a beginner and I want to know what is the correct way to debug the code and see the intermediate results of the run?

**Comment by pasenor** [comment]
Depends on your preferred setup for debugging, but you should (almost) always launch the generated `mycli` script.

If you use ipdb, then just install mycli with `pip install -e /path/to/mycli` (it links the source files instead of copying them, so that the changes are immediately reflected), and insert `import ipdb; ipdb.set_trace()` directly in the code.

If you use an IDE debugger, point it to bin/mycli as the executable.

**Comment by ThinkingAgain** [comment]
@pasenor Thank you for your patience in answering my question. I use `Pycharm` to debug the program, and now after setting the debug script to `/scripts/mycli-script.py`, I can do breakpoint debugging. Is this the right way to do it?

**Comment by pasenor** [comment]
yes, sounds right, have fun)
