### ISSUE TITLE
Make mycli options compatible with official mysql client

### ISSUE THREAD

**Issue by vtdmhd** [dbcli/mycli#118]
If this is done, existing workflow can be switched to mycli in 1 search and replace routine. Currently, for example, the --password option behaves differently

**Comment by amjith** [comment]
I'm trying to keep compatibility with mysql as much as possible. 

`--password` is a special case. 

I do have `--pass` which is an equivalent of the `--password` option in mysql. Will that be sufficient?

**Comment by morgo** [comment]
I have a similar request.  I use mysql locally mostly from mysql sandbox (as I think most DBAs do).

It would be a trivial patch to add something like `$MYSQL_EDITOR` to the `./use` program if mycli could understand the command line option `--defaults-file`.

/cc @datacharmer

**Comment by datacharmer** [comment]
Would it be useful if MySQL-Sandbox recognized a MYSQL_USE variable?

    export MYSQL_USE=mycli
    ./use

**Comment by morgo** [comment]
`MYSQL_EDITOR` is probably more consistent with existing environment variable usage? (Default text editor is `EDITOR`).

But yes, this is a useful feature.  If not for `mycli`, I would also consider it useful to be able to use the MySQL 5.7 command line client on all my sandboxes since it fixes Control-C support.

**Comment by datacharmer** [comment]
Since mycli does not recognize --defaults-file, it would require a special treatment to get the parameters. I tried it out, and works quite well.
However, this means that what we do for a mysql client would break mycli and vice versa.
I also realize that we need special cases for when ./use is invoked in batch mode (easy) and when it is invoked with "-e" (not so easy).
Probably the best solution is to have two scripts (they come cheap) so we will keep batch and interactive as separate worlds.

**Comment by amjith** [comment]
I'm a bit lost. I don't use mysql sandbox, so I'm not familiar with the `./use` command. 

Can I summarize your request as, you'd like mycli to have `--defaults-file` option?

**Comment by datacharmer** [comment]
MySQL Sandbox is a tool that installs one or more MySQL servers in the same host, and for each server creates also some customized scripts, so that the user does not need to use the MySQL client with many options. One such script is ./use, which invokes the MySQL client for the version that was installed, and uses a local my.cnf (./my.sandbox.cnf, in fact) to pass the sandbox options.
To use this file, the MySQL client is invoked with the option --defaults-file=/path/to/the/sandbox/my.sandbox.cnf.
Thus any tool that we want to invoke instead of the default client in this context needs to support the use of configuration files with the option --defaults-file.

**Comment by amjith** [comment]
Thank you for the clear and concise explanation. I'll add the `--defaults-file` option and change the `--password` option to take the password from the command line. One think I can't change is to make `-pPASSWORD` to work. That is non-posix and I can't get an option parser to work correctly in that situation.

**Comment by datacharmer** [comment]
To complement Morgan's request, I have added a ./mycli script to the ones generated by MySQL Sandbox. 
In [version 3.0.66](http://search.cpan.org/~gmax/MySQL-Sandbox-3.0.66/), you can use a sandbox with mycli by invoking the corresponding script. This script may become redundant in the future, but it is a nice addition.

**Comment by amjith** [comment]
I have added `--defaults-file` option and made `--password` option take in a password. Both changes are now in master. 

I'd like it if someone could test drive this and let me know if it is satisfactory. 
You can install directly from the git repo as follows: 

```
pip install https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by datacharmer** [comment]
At first try, it does not work. This is the content of the my.sandbox.cnf file:

    [mysql]
    prompt='mysql [\h] {\u} (\d) > '
    #
    
    [client]
    user               = msandbox
    password           = msandbox
    port               = 5708
    socket             = /tmp/mysql_sandbox5708.sock
    
    [mysqld]
    port               = 5708
    socket             = /tmp/mysql_sandbox5708.sock
    # ... more options

And this is the result:

    $ mycli --defaults-file=$HOME/sandboxes/msb_5_7_8/my.sandbox.cnf
    (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

**Comment by amjith** [comment]
My bad. It is now fixed. You can upgrade again from the master as follows: 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by datacharmer** [comment]
Thanks for the update. It works as expected!

**Comment by amjith** [comment]
This is now available in the latest version of mycli (1.3.0). I've made `-p` and `--password` act similar to mysql. The `--defaults-file` option is also added. 

Please upgrade.

**Comment by robsonpeixoto** [comment]
@amjith the `-p` parameter without a value should ask for the password. Today `mycli` returns the error:
```
Error: -p option requires an argument
```

**Comment by tsroten** [comment]
@robsonpeixoto There was a plan to make the password parameter ask for it, but I think it was blocked by an upstream issue. https://github.com/dbcli/mycli/issues/341
