### ISSUE TITLE
sqlparse version == 0.1.14 necessary?

### ISSUE THREAD

**Issue by aabmass** [dbcli/mycli#134]
I'm just wondering if the version requirement for sqlparse is necessary or if maybe `sqlparse >= 0.1.14` would work?

I am maintaining an unofficial package of mycli for Arch Linux in it's AUR and it would be a little easier with a more flexible dependency. The version of `python-sqlparse` and `python2-sqlparse` in our official repositories is currently `0.1.15`. Also, I see on PyPi that sqlparse is currently at version `0.1.16` as of late July.

EDIT: Ah, I see that it was pinned in 250a71d0022bbf1ae95f422bc3ab06ac75535d39.

Thank you in advance!

**Comment by amjith** [comment]
I've bumped it to 0.1.16. 

It was pinned to 0.1.14 because there was a bug in 0.1.15 that caused the completions to break. So I had to pin it. But it is now fixed in 0.1.16.

**Comment by aabmass** [comment]
Awesome, thank you! Fixed in ff5649792babaaa90cd72f76132bbd0fb16ae387

**Comment by aabmass** [comment]
How about the `'prompt_toolkit==0.46` frozen dependency from commit 8800287df7fb67cb20c456e9ddeb47644477d349?

**Comment by amjith** [comment]
That's a bit more tricky. `prompt_toolkit` is evolving a bit and the APIs are changing. I'm usually pretty good about upgrading prompt_tookit as soon as it comes out. Mainly because the library's author Jonathan sends a PR with the required API changes. 

If this is going to be a problem let me know, I'll talk to Jonathan and see what we can do.

**Comment by aabmass** [comment]
Ah, I see. Don't worry about it, I'll just keep an eye on the changes and work around it for now. Thanks for the help!
