### ISSUE TITLE
ctrl-w ctrl-w then ctrl-y

### ISSUE THREAD

**Issue by dbolser** [dbcli/mycli#151]
In emacs this will eat the last two words then paste them both. In mycli it eats two words then pasts only the last one eaten.

This is essentially the same as the ctrl-w fixed EditLine behaviour of the 5.6 client (which drove me here in the first place :-(

Awesome tool otherwise :-)

**Comment by amjith** [comment]
@dbolser The emacs copy/paste behavior is from prompt_toolkit the underlying library that powers mycli. 

You might want to file a bug with prompt_toolkit (https://github.com/jonathanslenders/python-prompt-toolkit).

**Comment by dbolser** [comment]
Thanks Amjith!

**Comment by dbolser-ebi** [comment]
https://github.com/jonathanslenders/python-prompt-toolkit/issues/158

**Comment by amjith** [comment]
Looks like it is now fixed. :)

Thanks for reporting it. I'll update to the new version of prompt_toolkit when it is released.

**Comment by tsroten** [comment]
@amjith Looks like it was released in [0.51](https://github.com/jonathanslenders/python-prompt-toolkit/commit/d2278549da0787c541185bcd5d6660fbb5140da6). But, now it's up to [0.52](https://github.com/jonathanslenders/python-prompt-toolkit/commit/949390c30af57b48e1738a7105ecc4d9afb835ad).

mycli is using 0.46. According to [python-prompt-toolkit's CHANGELOG](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG), these are backwards-incompatible changes since 0.46. In **bold** are the changes I know affect mycli. *Italics* are the changes that I'm unsure of. @amjith Does this look right? Or have I overlooked some?
- **There a now a `Lexer` abstract base class. Every lexer should be an instance
  of that class, and Pygments lexers should be wrapped in a `PygmentsLexer`
  class. `prompt_toolkit.shortcuts` still accepts Pygments lexers directly for
  backwards-compatibilty.**
- BufferControl no longer has a `show_line_numbers` argument. Pass a
  `NumberredMargin` instance instead.
- The `History` class became an abstract base class and only defines an
  interface. The default history class is now called `InMemoryHistory`.
- Removed deprecated 'tokens' attribute from GrammarLexer
- *Disable search by default in KeyBindingManager.*
- *Separated abort/exit key bindings. Disabled by default in KeyBindingManager.*
- *'Ignore' became the default on_abort action in `Application`.*
- *'Ignore' became the default accept_action in `Buffer`.*
- The layout processors have been refactored. The API is changed.
- `SwitchableValidator` has been renamed to `ConditionalValidator`.
- `WindowRenderInfo` has several incompatible changes.
- Margins have been refactored completely. Now it's the window that has the
  margin instead of `BufferControl`. Is is both much more performant and
  flexible.

**Comment by amjith** [comment]
@tsroten The author of prompt_toolkit @jonathanslenders created a PR against pgcli (https://github.com/dbcli/pgcli/pull/362) this morning. I haven't had a chance to review it, but that might be a good starting point to start the upgrade in mycli.

**Comment by tsroten** [comment]
@amjith Yes, great! @jonathanslenders I noticed you didn't wrap the `PostgresLexer` in a `PygmentsLexer` class. Would you recommend us wrapping `MySqlLexer` in a `PygmentsLexer`?

**Comment by jonathanslenders** [comment]
@tsroten : Good catch. I updated the pull request.

It's indeed better to wrap a pygments lexer classes in ``PygmentsLexer``. In order to stay backwards compatible, it's still allowed to be used directly. Maybe I remove that in the future.

**Comment by amjith** [comment]
@tsroten Are you planning to work on the upgrade? I don't want to duplicate our efforts. Let me know.

**Comment by tsroten** [comment]
@amjith I would love to, but I won't be able to get to it until next week. I am moving this weekend!

If you can't get to it before then, I'll work on it.

**Comment by amjith** [comment]
Released as part of 1.6.0. Please upgrade: 

```
pip install -U mycli 
```
