### ISSUE TITLE
Repeat column headings when using the pager

### ISSUE THREAD

**Issue by scottchiefbaker** [dbcli/mycli#224]
When I run a SQL query that returns thousands of rows mycli automatically turns on paging. If I scroll through several pages of data I can no longer see the column headings. If my columns consist of multiple numeric columns it's almost impossible to distinguish one column from the next unless I scroll **all** the way back to the top to read the headings again.

It would be very helpful to re-print the column headings at the top of each new page. Or at least make re-printing headings an option.

**Comment by tsroten** [comment]
@scottchiefbaker That's a great point. mycli passes off display duties to a pager (defaults to `less`). But, you can use other programs. Here is a way to use Vim to do what you want. While in some regards using vim as a pager like this isn't ideal, in other ways it is very powerful. You can tweak the results inline and write them to a file.

Add the following to your `[client]` section in `~/.my.cnf`:
```pager="vim -u NONE +2 -c 'set nomod|set scrollopt=hor|set nowrap|1split|windo set scrollbind|wincmd j' -"```

Now when you run a command in mycli, it will open the results in vim with a column header at the top of the page. You can scroll horizontally and the header will update accordingly. Scroll vertically and the header will stay there.

Here is an explanation of what the command does in case you aren't familiar with vim.

1. `-u NONE` makes vim not load any `.vimrc` files.
2. `+2` scrolls to the second line. This makes it so the column header text is visible in the top window of vim.
3. -c `....` runs the command in the quotation marks (in this case a series of `|`-separated commands:
  * `set nomod` quiets any messages like "No write since last change" when you try to exit vim
  * `set scrollopt=hor` makes it so that when we bind the two vim windows together, they only scroll together horizontally. This means that the top window will stay on the header.
  * `set nowrap` means that the lines won't wrap.
  * `1split` creates a one row split window at the top of vim that is used to display the column header.
  * `windo set scrollbind` binds the two windows together so they scroll with each other.
  * `wincmd j` puts the cursor in the second window.
4. `-` tells vim to read the standard input from mycli

To exit, type `:qa` and hit enter.

You could expand on this set up to your liking. You could even create a specific `.pager-vimrc` with your settings.

You could also see this discussion for more information: http://unix.stackexchange.com/questions/60507/how-to-scroll-large-datafile-while-keeping-header

**Comment by tsroten** [comment]
Closing since this is out-of-scope for mycli. Output is currently delegated to a configured pager.
