### ISSUE TITLE
Output format disorder when execute the query

### ISSUE THREAD

**Issue by re661b** [dbcli/mycli#264]
Hi
 I'm using mycli 1.6.0 on my pc. Output format disorder  when execute the query. 

mysql version:5.7.12
iterm2 version:2.1.4
![023bd31e-e9a8-4ed2-a9ca-eb1f72418600](https://cloud.githubusercontent.com/assets/12395952/15092753/9367584c-14a5-11e6-9142-0138ab98aa60.png)

Thanks any suggestions

**Comment by amjith** [comment]
The output looks jumbled because the lines are too long to fit in the screen. 

You can rerun your query as follows to get a vertically aligned output: 

```
select * from user\G
```

That will change the table output to display vertically so you can see the output. 

You said you're trying this in your PC, does that mean this is in Windows or is this in Linux? If you're in linux you can press "Shift-S" to disable wrapping of the columns which will show the output in the table format and you can scroll horizontally using left/right arrow. If you're in Windows, you won't be able to disable the wrapping of columns unless you're using `less` as your pager.

**Comment by re661b** [comment]
My mistake.I actually used osx 10.11.4 . in the iterm2 how can i fix this.

iterm2 version:2.1.4

thanks

**Comment by amjith** [comment]
Did you try pressing "Shift-S"? That will make the table not wrap around when the lines are longer. 

You can make that a permanent change by adding the following line your ~/.my.cnf file:

```
[client]
pager =  'less -SXRF'
```

You can also use the `\G` suffix as mentioned earlier to get a better output. 

```
select * from user\G
```

**Comment by re661b** [comment]
My problem has been solved

Thank you for your help.
