### ISSUE TITLE
Wrong output via pager 

### ISSUE THREAD

**Issue by Applemann** [dbcli/mycli#328]
Hello I upgraded mycli from old version 1.5.2 to newest 1.8.1 but now when I select table where width is longer then my screen so the table is printed ugly. In older version it was printed more pretty.
On attachment you can see the same table but in various version of mycli (1.5.2 and 1.8.1):
![screenshot from 2016-11-18 21-54-16](https://cloud.githubusercontent.com/assets/2686906/20446493/2834047a-adda-11e6-9056-03233d2ad88e.png)
Do you know where is problem??
Thanks

**Comment by amjith** [comment]
@Applemann Yes, I do. Mycli tries to use the pager that is specified in the $PAGER env var. If that var is empty and no pager is specified in your ~/.my.cnf file, then it will fall back to using `less -RXF`. In version 1.5.2 it used to fall back to using `less -SXRF`. Notice the difference in options. We dropped the `-S` from the default fallback option. That option made it so the output wouldn't wrap around. We had to drop it because it was ruining the scroll back behavior.

But the good news is you can get it back by setting a the `pager` option in your ~/.my.cnf under the [client] section. Here's an example from my local config. 

```
[client]
pager = 'less -XSRF'
```

**Comment by Applemann** [comment]
@amjith  Thank you very much. With this solution mycli is now working right :+1:
