### ISSUE TITLE
ctrl+c did not kill the query

### ISSUE THREAD

**Issue by chainkite** [dbcli/mycli#333]
After `ctrl+c`, the client told me the query is cancelled.
But actually, I can still see the query I just cancelled in `show processlist`.

I am using mycli 1.8.0 on Mac OS X, mysql server is v5.5

**Comment by amjith** [comment]
You are correct. I hadn't realized that this was happening. We'll need to add some logic to the Ctrl-C handling so we can actually kill the query in the server.

**Comment by chainkite** [comment]
Could you give me some hint about what additional logic and how it can be attached to Ctrl-C? Thx~

**Comment by amjith** [comment]
Sure thing. Ctrl-C is handled here: https://github.com/dbcli/mycli/blob/master/mycli/main.py#L553

You can kill a running query using the `kill` command. http://dev.mysql.com/doc/refman/5.7/en/kill.html

It gets a bit tricky to find out which query was just canceled. 

You can get a list of all the queries in flight using `show full processlist` command. The first column in that result tells you the process id that you need to use in order to kill that query.

You have access to the query in mycli in the variable `document.text`. So technically in that `except` block you can run the `show full processlist` command and then parse the output to find out the pid and subsequently call a kill command to cancel that query.

Are you planning to work on this?

**Comment by chainkite** [comment]
Sry @amjith , I am not quite familiar with python language.

**Comment by chainkite** [comment]
@amjith , I am on holiday now. I am trying to work this issue. Thx~
