### ISSUE TITLE
Make edit command default to previous query

### ISSUE THREAD

**Issue by fpietka** [dbcli/mycli#35]
I am wondering, on psql when triggering `\e` on a new line, it will edit previous query. Here we have to append it to the query itself. Is that a design choice?
I must say that if not, I'd like to have that feature :grin:

**Comment by tsroten** [comment]
It looks like mysql does this as well. It can tell the difference between a command and a query, so the editor will only ever display the last query.

For example, here is a sample narrative:
- `use my_db`
- `edit` -- editor opens blank
- `select count(*) from my_table;`
- `edit` -- editor opens with previous query
- `use my_db_number_2`
- `edit` -- editor opens with same query as before (`select count(*)...`)

**Comment by amjith** [comment]
I'm not sure if we need to emulate exactly what mysql does. I feel like we can just edit whatever was the previous command. 

Simply because there are many corner cases like what if the previous command was a multi-query separated by semi-colons and one of them happens to be `use my_db`? 

At least for the first attempt let's do just previous command and so special cases.

**Comment by tsroten** [comment]
Agreed 👍

**Comment by tsroten** [comment]
@fpietka This is included as of version 1.11.0. If you installed via `pip`, you can upgrade by running `pip install --upgrade mycli`.

Thanks for the idea!

**Comment by fpietka** [comment]
Great, thanks!
