### ISSUE TITLE
special command \e doesn't work with prompt_toolkit>=1.0.10

### ISSUE THREAD

**Issue by meeuw** [dbcli/mycli#377]
Special command \e doesn't seem to work with new version of prompt_toolkit

Steps to reproduce:
1. `mysql root@172.17.0.2:(none)> select 1\e` 
2. change 1 to 2 in editor, save/quit

Expected (works with prompt_toolkit==1.0.9):
`mysql root@172.17.0.2:(none)> select 2` 

Actually (with prompt_toolkit>=1.0.10)
`mysql root@172.17.0.2:(none)> `

**Comment by meeuw** [comment]
we might want to change setup.py d41c29f1dd275df811af57ba376b5b742afac149

**Comment by tsroten** [comment]
A workaround in mycli's Vi-mode is to hit <Esc>, then hit `v` to bring up the editor. Editing and saving the contents will correctly edit (and immediately execute) the query.

**Comment by tsroten** [comment]
I think it has something to do with [this change](https://github.com/jonathanslenders/python-prompt-toolkit/commit/903018201e0b0f5ad4090c08879fa83f665413b3).

I'll take a look at it later and see if there is an easy way to fix it on mycli's side without changing `setup.py`, otherwise, we can bump it down like you suggested.

**Comment by tsroten** [comment]
Homebrew was just updated with mycli 1.9.0 and prompt toolkit 1.0.13 :(

**Comment by amjith** [comment]
I know that @j-bennet has a fix for it in pgcli. Not yet merged. Maybe she
can shed some light.

On Mar 20, 2017 7:11 AM, "Thomas Roten" <notifications@github.com> wrote:

Homebrew was just updated with mycli 1.9.0 and prompt toolkit 1.0.13 :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dbcli/mycli/issues/377#issuecomment-287770243>, or mute
the thread

**Comment by tsroten** [comment]
Thanks @amjith! Here is the issue for reference: https://github.com/dbcli/pgcli/issues/668
And, the pull request: https://github.com/dbcli/pgcli/pull/670

**Comment by j-bennet** [comment]
Fix is now in master.

**Comment by tsroten** [comment]
mycli version 1.10.0 is now out which fixes this.
