### ISSUE TITLE
ImportError: No module named wcwidth

### ISSUE THREAD

**Issue by basebase** [dbcli/mycli#391]
My site Mac OS run main.py
is error ->

ImportError: No module named wcwidth

> Traceback (most recent call last):
  File "/Users/Joker/Documents/code_framework/python/mycli/mycli/main.py", line 26, in <module>
    from prompt_toolkit import CommandLineInterface, Application, AbortAction
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/__init__.py", line 16, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/interface.py", line 19, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/application.py", line 3, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/buffer.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/auto_suggest.py", line 13, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/filters/__init__.py", line 33, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/filters/base.py", line 5, in <module>
  File "build/bdist.macosx-10.11-intel/egg/prompt_toolkit/utils.py", line 9, in <module>

**Comment by meeuw** [comment]
Hi @basebase how did you install mycli? `wcwidth` is a dependency for mycli and it seems it isn't installed on your system. You could try to install it using `pip install wcwidth`.

**Comment by basebase** [comment]
Hi @meeuw I using pip install wcwidth.

> The directory '/Users/Joker/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Joker/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: wcwidth in ./Library/Python/2.7/lib/python/site-packages

**Comment by meeuw** [comment]
@basebase this seems to be a permission problem, I don't know how comfortable you are with Python?

Maybe it helps if you install mycli in a virtualenv, by using the following commands:
```
virtualenv mycli
cd mycli
bin/pip install mycli
bin/mycli
```

**Comment by j-bennet** [comment]
@basebase You're not supposed to start the CLI by running `main.py`. After you installed mycli, simply run:

```
$ mycli
```

from command line.

**Comment by basebase** [comment]
@j-bennet @meeuw 
I'm through brew install mycli
But I want to see is how to operate

python version => 2.7

**Comment by j-bennet** [comment]
So this happens when you run `mycli` command?

**Comment by basebase** [comment]
@j-bennet 
I'm Run mycli command is not happens

**Comment by j-bennet** [comment]
Now I'm confused. :) Are you having this issue running `mycli` or not?

**Comment by basebase** [comment]
@j-bennet 
brew install mycli run mycli command is not happens.
I'm Import mycli source code to pycharm run main.py is error
I want to run the source program.

sudo pip install mycli Is also wrong

**Comment by tsroten** [comment]
@basebase Could you please paste all the error messages that happen when you run this?
```bash
$ sudo pip uninstall mycli
$ sudo pip install mycli
$ mycli
```

Thanks!

**Comment by basebase** [comment]
@tsroten 
I choose to python 3.5.0 
pip install is sucess

I want to know how to deploy the source code
import pycharm run main.py 

 from .packages.tabulate import tabulate, table_formats
ValueError: Attempted relative import in non-package

**Comment by amjith** [comment]
I think I vaguely understand your question. Here's my attempt at answering that. 

First, if you just want to use mycli then you can do that without pycharm. All you have do is: 

1. pip install mycli    # This will install mycli and all dependencies.
1. mycli                    # Launch mycli from the commandline and start using.

Second, if you're interested in developing mycli and digging into the code I can understand why you'd want to use pycharm. But the challenge is that you can't run the code from inside PyCharm (@j-bennet correct me if I'm wrong). The reason you can't run it directly from inside pycharm is because `mycli` is a command line application. It needs to run inside a terminal. So trying to launch it from inside PyCharm will fail to work. 

If you're interested in making code changes and seeing the effect, we have a detailed DEVELOP workflow here: https://github.com/dbcli/mycli/blob/master/DEVELOP.rst

If you're still having trouble getting the local development setup, reply here with what steps you've tried and what errors you're seeing. We're all very helpful people and we can help you sort through the issues.

**Comment by j-bennet** [comment]
@amjith is correct, you won't be able to run from under pycharm, you need a proper terminal environment. But you can absolutely use pycharm for development, and a virtualenv setup (as described in DEVELOP guide) to see the effect of your changes.

**Comment by basebase** [comment]
Thanks All

**Comment by tsroten** [comment]
@basebase Thanks for using mycli! I'm going to close this issue for now. If you have any other issues, feel free to let us know, thanks!
