### ISSUE TITLE
How do I install mycli 1.8.1 on Ubuntu?

### ISSUE THREAD

**Issue by mikeerickson** [dbcli/mycli#399]
I have installed mycli using `apt-get` but it installed v1.5.2

Have you updated `apt-get` library so that i can install version 1.8.1

Note:  I dont want to use 1.9 due to the changes it applies to the output

**Comment by tsroten** [comment]
Hi @mikeerickson! It looks like some of the Ubuntu packages are [a bit behind](http://packages.ubuntu.com/search?keywords=mycli). 

Installing via `pip` is probably the way to go, like you're doing in #400. Try installing the python development package first, since pycrypto needs it:
```$ apt-get install python-dev```

Then try to install mycli. I hope that helps!

**Comment by tsroten** [comment]
I'm wondering, when you say:
> I dont want to use 1.9 due to the changes it applies to the output

What changes to the output are you referring to?

**Comment by mikeerickson** [comment]
@tsroten yes that is correct (376 explains). I will give it a whirl with the command you recommended.

**Comment by mikeerickson** [comment]
@tsroten I wound up getting it working installing 1.8.1 using pip.

**Comment by tsroten** [comment]
@mikeerickson Great! I'm glad to hear that. Let us know if we can help with anything else :)

**Comment by orioljd** [comment]
Hello, in apt and snap is outdated now is 1.8.1 version
