### ISSUE TITLE
Specifiying username: inconsistency with pgcli

### ISSUE THREAD

**Issue by shtrom** [dbcli/mycli#492]
`mycli` takes `-u` as the option flag to specify the user; `pgcli` uses `-U`. This is confusing (I had to check before writing this issue, to make sure I got them right; and I didn't...).

Could those two be unified?

See also, dbcli/pgcli#776

**Comment by tsroten** [comment]
Thanks for pointing this out :smile: Conversation starting in the pgcli issue: https://github.com/dbcli/pgcli/issues/776

**Comment by tsroten** [comment]
To sum up the discussion over at https://github.com/dbcli/pgcli/issues/776, it was decided that mycli should not use the `-U` flag for username because the official mysql client uses `-U` for safe updates, a feature we might want to add to mycli in the future.

So, I'm going to close this issue. @shtrom Thanks for bringing this up -- it was a good idea!
