### ISSUE TITLE
Show on Iterm

### ISSUE THREAD

**Issue by MrLevo520** [dbcli/mycli#498]
Hi, i find the result will show with 'less',but if i want my result show just on my iterm and i want to check it out when i write another sql, can you help me ? thank you !

**Comment by tsroten** [comment]
Hello @MrLevo520! There are a few ways you can configure the pager. Based on what you said, I'd suggest one of these:
1. Disable the pager altogether
2. Make it so that the pager output stays on the screen when you quit it (the `-X` option for `less`).

We have a page that should show you how to set this up. Feel free to let us know if you need any help configuring it:
http://www.mycli.net/pager

**Comment by MrLevo520** [comment]
Hi Roten:
Thank you very much! That’s what I am talking about ! It’s show just I want !
BTW,i suggest the option of ‘nopage’ should set as default, it’s just my advice，LOL, thank you again, it’s just Awesome!
在 2017年8月15日，上午12:53，Thomas Roten <notifications@github.com<mailto:notifications@github.com>> 写道：


Hello @MrLevo520<https://github.com/mrlevo520>! There are a few ways you can configure the pager. Based on what you said, I'd suggest one of these:

  1.  Disable the pager altogether
  2.  Make it so that the pager output stays on the screen when you quit it (the -X option for less).

We have a page that should show you how to set this up. Feel free to let us know if you need any help configuring it:
http://www.mycli.net/pager

**Comment by tsroten** [comment]
@MrLevo520 I'm glad it's working! Thanks for the advice!
