### ISSUE TITLE
Mycli Crashes When Unable to Read Login Path File

### ISSUE THREAD

**Issue by Peter-Sh** [dbcli/mycli#508]
I've just installed mycli in debian 9 using official repository and the tool fails to start

```Traceback (most recent call last):
  File "/usr/bin/mycli", line 11, in <module>
    load_entry_point('mycli==1.8.1', 'console_scripts', 'console')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/mycli/mycli/main.py", line 769, in cli
    auto_vertical_output=auto_vertical_output, warn=warn)
  File "/usr/share/mycli/mycli/main.py", line 158, in __init__
    mylogin_cnf = open_mylogin_cnf(mylogin_cnf_path)
  File "/usr/share/mycli/mycli/config.py", line 103, in open_mylogin_cnf
    plaintext = read_and_decrypt_mylogin_cnf(f)
  File "/usr/share/mycli/mycli/config.py", line 172, in read_and_decrypt_mylogin_cnf
    pplain = aes_cipher.decrypt(cipher)
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```
It does not start even if I supply username and password in the args.

It seems this is because mycli expects credentials in mylogin.cnf file. But the problem is that MariaDb (which is official mysql server and client for RedHat, CentOS and Debian) does not have mysql_config_editor. (And I think will [never](https://mariadb.com/resources/blog/mysql-56-security-through-complacency) has) So starting mycli tool becomes hard if ever possible.

I think mycli may read or at least fall back to plain ~/.my.cnf file just like mysql standard client does to avoid confusion with MariaDb users. Or maybe just don't try to read encrypted file if credentials are provided in command line.

Thank you!

**Comment by tsroten** [comment]
@Peter-Sh Thanks for reporting this! Mycli doesn't require an encrypted credentials file. Since it's a user's configuration file, we have to read it if it's there. For example, if you provided the username and host via the command line, the encrypted file could still potentially provide the port/socket to use. This, in general, should not cause problems.

In your case, this error message is saying that there a problem with the encryption scheme in the file. It sounds like you aren't using the encrypted file, so I'd suggest moving/removing the file `~/.mylogin.cnf` and seeing if that fixes it.

If the encrypted file is not there, mycli is designed to start up without it.

If you don't think you have this file (`~/.mylogin.cnf`), you might want to look at mycli's log to see which file it is loading:
1. Set the mycli `log_level` to `DEBUG` (in your `myclirc` file).
2. Start up mycli.
3. Look at mycli's log (defaults to `~/.mycli.log`) and look for a line that says this: `Found login path file at...`).

**Comment by Peter-Sh** [comment]
@tsroten Thanks, you are absolutely right! I have found ~/.mylogin.cnf with plain text, It was created 2 years ago, so did not expect it is there. I've deleted the file and mycli started to work.
Sorry for this, it is really not an issue :)

**Comment by tsroten** [comment]
@Peter-Sh No problem! I'm glad you figured it out. If you don't mind, I'm going to reopen this issue so we can work on handling login path file errors in a more user-friendly manner.

**Comment by Peter-Sh** [comment]
I think it is good idea to make a friendly error message instead of a back trace :)

**Comment by tsroten** [comment]
Mycli now handles this error without crashing as of version 1.13.1.

@Peter-Sh Thanks again for reporting this!
