### ISSUE TITLE
when enter, it will go to vim mode

### ISSUE THREAD

**Issue by fhq** [dbcli/mycli#548]
when enter, it will go to vim mode。
I don't want to this. how can I do for it.

**Comment by amjith** [comment]
You can disable the vim mode by editing the config file located under `~/.myclirc`. 

Look for the line that says `keybinding`. 

set it to 

```
key_bindings = emacs
```

That should make it so that it won't put you in the vim mode. 

If that doesn't solve your problem give a little bit more info on what you see and we can help.

**Comment by tsroten** [comment]
@fhq I hope Amjith's information helped you! I'm going to close this issue. Feel free to open it again if you have any more trouble. Thanks!
