### ISSUE TITLE
Error on pip install on CentOS 7

### ISSUE THREAD

**Issue by StewAlexander-com** [dbcli/mycli#825]
Error:

```
ERROR: Cannot uninstall 'configobj'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
----

```
[support@glyptodon ~]$ cat /etc/*release
CentOS Linux release 7.7.1908 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```
Python 2.7.5

**Comment by pasenor** [comment]
Hi, you probably have package `python-configobj` installed (check with `yum info python-configobj`). On Centos 7 it has lower version than what mycli requires, and it cannot be upgraded by pip. You have two easy options:

1. remove the system package manually: `yum erase python-configobj`, then `pip install --upgrade mycli` will install a newer version as a dependency. However, be cautious: if some other application depended on that earlier `configobj` version, it may break after the update. 

2. Install python3 and use its ecosystem for mycli:
`yum install python3`
`pip3 install mycli`
I'd recommend the second option, especially since python2 support is going to be deprecated with the next mycli release.

**Comment by StewAlexander-com** [comment]
I'll check & report back, thanks for the feedback
